name: Development workflow

on:
  push:
    branches:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Development Code
        uses: actions/checkout@v2
      - name: Use Node.js 19.9
        uses: actions/setup-node@v1
        with:
          node-version: 19.9
      - run: npm install
      - run: npm run build
      - run: npm run lint
